-- 공사현장: 수주.공사현장 드롭다운 옵션 소스. 수주.공사현장은 문자열로 유지(비정규화, A-1).
-- 공사이력.준공정산: 준공 시 자동 생성되는 정산 행 식별 플래그(B-1).
-- 선행: 20260622090000_rls_whitelist_helper.sql(is_whitelisted), 20260622090300_rls_admin_writes.sql(is_admin)

create table if not exists public.공사현장 (
  id        bigint generated by default as identity primary key,
  현장명     text not null unique,
  생성일     timestamptz not null default now()
);

alter table public.공사현장 enable row level security;

-- 읽기: 화이트리스트 사용자 전체 / 쓰기: admin 전용 (거래처·공사단가와 동일 정책)
create policy 공사현장_select_whitelisted on public.공사현장
  for select to authenticated using ((select public.is_whitelisted()));
create policy 공사현장_insert_admin on public.공사현장
  for insert to authenticated with check ((select public.is_admin()));
create policy 공사현장_update_admin on public.공사현장
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy 공사현장_delete_admin on public.공사현장
  for delete to authenticated using ((select public.is_admin()));

-- 시드: 기존 수주.공사현장 distinct 값 + 광명·안양
insert into public.공사현장 (현장명)
select distinct trim(공사현장)
from public.수주
where 공사현장 is not null and trim(공사현장) <> ''
on conflict (현장명) do nothing;

insert into public.공사현장 (현장명) values ('광명'), ('안양')
on conflict (현장명) do nothing;

-- 공사이력 준공정산 플래그
alter table public.공사이력
  add column if not exists 준공정산 boolean not null default false;
