-- supabase/migrations/20260713090000_materials.sql
-- 자재관리(케이블 드럼 단위 추적 + 기타 자재).
-- 설계: 잔량·수량 컬럼 없음 — 기록(원본)에서 조회 시 파생.
--       (별도 컬럼 = 원본을 고치는 모든 경로에 갱신 의무 → 누락 시 재고가 조용히 어긋남)
-- 선행: 20260622090000(is_whitelisted), 20260622090300(is_admin), 20260624120000(audit_trigger)

-- 1) 케이블 선종 — 참조 테이블, 쓰기 admin 전용(공사현장 관례)
create table public.자재_선종 (
  id    bigint generated by default as identity primary key,
  코드  text not null unique,
  전압  text not null check (전압 in ('고압','저압')),
  정렬  int  not null default 0
);

-- 2) 케이블 드럼 — 물리 드럼 1개 = 1행. 입고 = 드럼 생성.
create table public.자재_드럼 (
  id         bigint generated by default as identity primary key,
  선종_id    bigint not null references public.자재_선종(id),
  초기길이   numeric not null check (초기길이 > 0),
  제조표기   text,                    -- 제조사·제조년월 자유 표기 (예: '대일 26.02')
  입고일     date not null,
  사용처공사 text,                    -- 입고 때 적는 사용처 (출고 공사명과 별개 칸)
  입고묶음   uuid not null,           -- 한 번의 입고 등록 그룹(피드 "450m ×3" 묶음 표시용)
  생성일     timestamptz not null default now(),
  작성자     uuid default auth.uid()
);
create index 자재_드럼_선종_idx on public.자재_드럼 (선종_id);

-- 3) 드럼 출고 기록 — 사용량 null = 출고 중(미복귀). 잔량 = 초기길이 - Σ사용량 (조회 시 계산)
create table public.자재_드럼기록 (
  id       bigint generated by default as identity primary key,
  드럼_id  bigint not null references public.자재_드럼(id) on delete cascade,
  출고일   date not null,
  공사명   text not null,
  사용량   numeric check (사용량 >= 0),
  복귀일   date,                      -- 사용량 기입 시점(출고 때 바로 적으면 = 출고일)
  출고묶음 uuid not null,
  생성일   timestamptz not null default now(),
  작성자   uuid default auth.uid(),
  -- 사용량과 복귀일은 한 쌍: 미기입(출고 중)이면 둘 다 null, 기입(복귀)이면 둘 다 채운다
  constraint 자재_드럼기록_사용량_복귀일_쌍 check ((사용량 is null) = (복귀일 is null))
);
create index 자재_드럼기록_드럼_idx on public.자재_드럼기록 (드럼_id);

-- 4) 기타 자재 품목 — 참조 테이블, 쓰기 admin 전용
create table public.자재_품목 (
  id    bigint generated by default as identity primary key,
  분류  text not null,
  품명  text not null,
  단위  text not null default '개',
  정렬  int  not null default 0,
  unique (분류, 품명)
);

-- 5) 기타 자재 수량 기록 — 현재수량 = Σ변화량 (조회 시 계산)
create table public.자재_품목기록 (
  id       bigint generated by default as identity primary key,
  품목_id  bigint not null references public.자재_품목(id),
  변화량   int not null check (변화량 <> 0),   -- +입고 / -출고
  일자     date not null,
  공사명   text,
  생성일   timestamptz not null default now(),
  작성자   uuid default auth.uid()
);
create index 자재_품목기록_품목_idx on public.자재_품목기록 (품목_id);

-- RLS: 마스터 2개(선종·품목)는 읽기 화이트리스트/쓰기 admin, 기록 3개는 화이트리스트 전 작업
do $$
declare t text;
begin
  foreach t in array array['자재_선종','자재_드럼','자재_드럼기록','자재_품목','자재_품목기록'] loop
    execute format('alter table public.%I enable row level security;', t);
    execute format($f$
      create policy %I on public.%I for select to authenticated
        using ((select public.is_whitelisted()));
    $f$, t || '_select_whitelisted', t);
  end loop;

  -- 기록 테이블: 화이트리스트 insert/update/delete
  foreach t in array array['자재_드럼','자재_드럼기록','자재_품목기록'] loop
    execute format($f$
      create policy %I on public.%I for insert to authenticated
        with check ((select public.is_whitelisted()));
    $f$, t || '_insert_whitelisted', t);
    execute format($f$
      create policy %I on public.%I for update to authenticated
        using ((select public.is_whitelisted())) with check ((select public.is_whitelisted()));
    $f$, t || '_update_whitelisted', t);
    execute format($f$
      create policy %I on public.%I for delete to authenticated
        using ((select public.is_whitelisted()));
    $f$, t || '_delete_whitelisted', t);
  end loop;

  -- 마스터 테이블: admin 쓰기
  foreach t in array array['자재_선종','자재_품목'] loop
    execute format($f$
      create policy %I on public.%I for insert to authenticated
        with check ((select public.is_admin()));
    $f$, t || '_insert_admin', t);
    execute format($f$
      create policy %I on public.%I for update to authenticated
        using ((select public.is_admin())) with check ((select public.is_admin()));
    $f$, t || '_update_admin', t);
    execute format($f$
      create policy %I on public.%I for delete to authenticated
        using ((select public.is_admin()));
    $f$, t || '_delete_admin', t);
  end loop;
end $$;

-- 변경내역 추적 (기존 audit_trigger 재사용)
create trigger audit_자재_선종     after insert or update or delete on public.자재_선종     for each row execute function public.audit_trigger();
create trigger audit_자재_드럼     after insert or update or delete on public.자재_드럼     for each row execute function public.audit_trigger();
create trigger audit_자재_드럼기록 after insert or update or delete on public.자재_드럼기록 for each row execute function public.audit_trigger();
create trigger audit_자재_품목     after insert or update or delete on public.자재_품목     for each row execute function public.audit_trigger();
create trigger audit_자재_품목기록 after insert or update or delete on public.자재_품목기록 for each row execute function public.audit_trigger();

-- 시드: 선종 (재고 데이터는 넣지 않는다 — 빈 재고로 시작, 실사 후 입고 기능으로 입력)
insert into public.자재_선종 (코드, 전압, 정렬) values
  ('CA400','고압',1),('CA95','고압',2),('CE60','고압',3),
  ('CE325','고압',4),('CE240','고압',5),('CE600','고압',6),
  ('35SQ','저압',1),('70SQ','저압',2),('120SQ','저압',3),('240SQ','저압',4);

-- 시드: 기타 자재 품목명 (수기 대장의 실제 품목 — 수량은 0에서 시작)
insert into public.자재_품목 (분류, 품명, 단위, 정렬) values
  ('CU 접속재','직선용 325','개',1),('CU 접속재','직선용 60','개',2),
  ('CU 접속재','PAD용 325','개',3),('CU 접속재','PAD용 60','개',4),
  ('CU 접속재','TR엘보 접속재','개',5),('CU 접속재','종단 60','개',6),
  ('AL 접속재','직선용 95','개',1),('AL 접속재','직선용 400','개',2),
  ('AL 접속재','PAD용 240','개',3),('AL 접속재','TR엘보 접속재','개',4),
  ('AL 접속재','종단 240','개',5),
  ('개폐기','3DM','대',1),('개폐기','4DM','대',2),('개폐기','4DA','대',3),
  ('개폐기','에폭시 4DA','대',4),('개폐기','다회로','대',5),
  ('변압기','단상 100kVA','대',1),('변압기','삼상 150kVA','대',2),
  ('변압기','삼상 300kVA','대',3),('변압기','삼상 500kVA','대',4);
